### ISSUE TITLE
Couldn't download SAPUI5 zip archive

### ISSUE THREAD

**Issue by jberthe** [bastilimbach/sapui5-runtime#8]
Hi,

On my system I cannot download the archive.

I have done the SET PROXY command (http and https).

> 
>  npm install -D sapui5-runtime
> 
> > sapui5-runtime@1.4.0 postinstall C:\local\*******\My Documents\VSCodeWorkspace\z************\node_modules\sapui5-runtime
> > node src/install.js
> 
> By using this npm package you agree to the EULA from SAP: https://tools.hana.ondemand.com/developer-license-3_1.txt/
> Downloading SAPUI5...
> Error: Couldn't download SAPUI5 zip archive from 'https://tools.hana.ondemand.com/additional/sapui5-rt-1.52.8.zip'
>     at downloadSAPUI5 (C:\local\*********\My Documents\VSCodeWorkspace\z*************\node_modules\sapui5-runtime\src\install.js:101:11)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (node:14940) UnhandledPromiseRejectionWarning: Error: Couldn't download SAPUI5 zip archive from 'https://tools.hana.ondemand.com/additional/sapui5-rt-1.52.8.zip'
>     at downloadSAPUI5 (C:\local\***********\My Documents\VSCodeWorkspace\z***********\node_modules\sapui5-runtime\src\install.js:101:11)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (node:14940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:14940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will
> terminate the Node.js process with a non-zero exit code.
> npm WARN zqm_wizard_notification@1.0.0 No description
> 
> + sapui5-runtime@1.4.0
> updated 1 package and audited 14 packages in 2.127s
> found 0 vulnerabilities
> 

Regards,
Joseph

**Comment by bastilimbach** [comment]
Hi @jberthe thanks for reporting the issue! 

Could you try removing the `HTTP_PROXY` environment variable and only using the https proxy?

It’s quite hard for me to debug theses issues as I don’t have the required proxy’s. Neither at work nor at home 😕

If the change to only using HTTPS doesn’t work I will create a new branch with better error handling which hopefully logs a useful error so I can analyse your problem further.

**Comment by bastilimbach** [comment]
It just came to my mind that I could simple spin up a docker container which serves as a local proxy instance to test your scenario. I’ll try that later 👍

**Comment by bastilimbach** [comment]
One last thing, could you send me your proxy config?

**Comment by webast** [comment]
Hi guys,

I'm facing the same error despite my proxy settings...
The proxy settings seems to works with other npm plugins' install

Regards,
Sébastien

```
By using this npm package you agree to the EULA from SAP: https://tools.hana.ondemand.com/developer-license-3_1.txt/
Downloading SAPUI5...
Error: Couldn't download SAPUI5 zip archive from 'https://tools.hana.ondemand.com/additional/sapui5-rt-1.60.19.zip'
    at downloadSAPUI5 (C:\Users\xxxxxxxxx\node_modules\sapui5-runtime\src\install.js:101:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:36704) UnhandledPromiseRejectionWarning: Error: Couldn't download SAPUI5 zip archive from 'https://tools.hana.ondemand.com/additional/sapui5-rt-1.60.19.zip'
    at downloadSAPUI5 (C:\Users\xxxxxxxxx\node_modules\sapui5-runtime\src\install.js:101:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:36704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:36704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jberthe** [comment]
Hi,
Here is the proxy configuration :

> set HTTP_PROXY=http://uiserid:P%40sse%242019@my.proxy.local:8080
> set HTTPS_PROXY=http://uiserid:P%40sse%242019@my.proxy.local:8080

I have delete the HTTP_PROXY and the error is the same.
Regards,
Joseph

**Comment by bastilimbach** [comment]
Ah ok, I think I know what the issue is. The `HTTPS_PROXY` is configured with at `http://`origin. This is something the package currently doesn't support. I'll take a look 👍

**Comment by webast** [comment]
I have the same proxy configuration as Joseph. 
I tested `HTTPS_PROXY` with `http://` and` https://` and the issue is the same for me.

**Comment by bastilimbach** [comment]
Thanks for all the testing 👍 
I'll provide a fix for it as soon as I can spin up a local test proxy

**Comment by webast** [comment]
You're welcome. Thank you for your work.

**Comment by jberthe** [comment]
it's a plaisure :) I have found a workaround by downloading mannully the library :)
Great work, keep going 👍

**Comment by bastilimbach** [comment]
I just pushed a fix (3d11cb6c35f67ef7ef2cd9dc10406bb3128aedae). Now every proxy configuration should be supported. I could reproduce the error using a local proxy instance. With version 1.4.1 this issue was solved on my side. @webast @jberthe Could you confirm, that it is also working for you guys?

**Comment by webast** [comment]
It works like a charm for me. :thumbsup:
Thank you @bastilimbach !

**Comment by bastilimbach** [comment]
Awesome 🎉
